### ISSUE TITLE
metaPCA default usage

### ISSUE THREAD

**Issue by Caleb-Huo** [metaOmic/metaPCA#2]
I pulled the latest metaPCA from feature/metaPCA.
I tried default setting. I encounter the following error message.
![screen shot 2016-09-19 at 11 39 25 pm](https://cloud.githubusercontent.com/assets/6474826/18656813/81845864-7ec2-11e6-87e6-8a132de4f06f.png)

**Comment by CHPGenetics** [comment]
Is this solved?

**Comment by Caleb-Huo** [comment]
Yes, using "unlist" trick
